config/routes.rb
Mybet::Application.routes.draw do

  resources :bids
  resources :users

  resources :bets do
    member do
      put :bid
      get :duplicate
    end
    collection do
      get :pending
    end
  end

  root :to => "dashboard#index"

  put "/dashboard/:id/update" => "dashboard#update", :as => "dashboard_update"
  get "/reports" => "dashboard#reporting", :as => "reporting"
  devise_for :users, :path => "/authenticate"

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :only_admin

  def index
    @bets = Bet.where("state != 'new'")

    if params[:state]
      @bets = @bets.where(:state => params[:state])
    end
    @options = [
        ["All Bets", root_path],
        ["Won Bets", root_path(:state => "won")],
        ["Lost Bets", root_path(:state => "lost")],
        ["Pending Bets", root_path(:state => "pending")]
    ]
  end


  def update
    @bet = Bet.find(params[:id])
    @bet.send(params[:e].to_sym)
  end

  def reporting
    @bets = Bet.won_or_lost
  end
end

app/views/dashboard/_well_content.html.erb
<td><%= "#{bet.name} | #{bet.id}" %>     </td>
<td><%= number_to_currency bet.bid_amount %></td>
<td><%= bet.bids.count %></td>
<td><%= bet.original_odds %></td>
<td>+<%= number_with_precision bet.calculated_final_odds, :precision => 2 %></td>
<td>
            <span class="label label-<%= bet.state %>"><%= bet.state.titleize %>
                                </span>
</td>
<td>
  <% bet.next_state_events.each do |e| %>
      <%= link_to e.event.to_s.titleize, dashboard_update_path(bet, :e => e.event), :class => "btn btn-#{e.event} btn-mini", :method => :put, :confirm => "Are you sure?", :remote => true %>
  <% end %>
</td>

<td>

    <div class="btn-group">
      <button class="btn btn-primary">
        Actions
      </button>
      <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li>
          <%= link_to_with_icon "icon-edit", "Edit", edit_bet_path(bet) %>
        </li>
        <li>
          <%= link_to_with_icon "icon-repeat", "Duplicate", duplicate_bet_path(bet) %>
        </li>
        <li>
          <%= link_to_delete bet, :url => bet_path(bet), :remote => true %>
        </li>
      </ul>
    </div>

</td>

app/views/dashboard/index.html.erb
<div class="page-header">
  <div class="pull-left">
    <h1>Dashboard
      <% if params[:state] %>
      <small><%= "#{params[:state].titleize} Bets" %></small>
      <% end %>
    </h1>
  </div>
  <div class="pull-right header-button">
    <%= select_tag "filter", options_for_select(@options), :prompt => "Filter Bets", :class => "filter-select" %>
  </div>
  <div class="clearfix"></div>
</div>

<table class="table table-bordered">
  <thead>
  <tr>
    <th>Name | ID</th>
    <th>Bid Amount</th>
    <th>Amount of Bids</th>
    <th>Original Odds</th>
    <th>Final Odds</th>
    <th colspan="2">Current Status</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @bets.each do |bet| %>
      <tr id="well-content-<%= bet.id %>">
        <%= render :partial => "well_content", :locals => {:bet => bet} %>
      </tr>
  <% end %>
  </tbody>
</table>

<script>
    $('.filter-select').on('change', function () {
        window.document.location.href = $(this).val();
    });
</script>

app/views/dashboard/reporting.html.erb
<div class="well">

  <div class="page-header">
    <h1>OVERALL REPORTING</h1>
  </div>

  <table class="table table-striped table-bordered">
    <thead>
    <tr>
      <th>Name | ID</th>
      <th>Username</th>
      <th>Bid Amount Earned</th>
      <th>Potential Payout</th>
      <th>Gross Bet Earnings</th>
      <th>Status</th>
    </tr>
    </thead>
    <tbody>
    <% @bets.each do |bet| %>

        <tr>
          <td><%= "#{bet.name} | #{bet.id}" %></td>
          <td><%= bet.user.username %></td>
          <td><%= number_to_currency bet.bid_amount_earned %></td>
          <td><%= number_to_currency bet.potential_payout %></td>
          <td><%= number_to_currency bet.gross_bet_earnings %></td>
          <td><span class="label label-<%= bet.state %>"><%= bet.state %> </span></td>
        </tr>

    <% end %>
    </tbody>
  </table>
</div>
<hr>
<div class="well">
  <h1>FULL SUMMARY</h1>
  <hr>
  <table class="table table-striped table-bordered table-full-summary">
    <thead>
    <tr>
      <th>TOTAL EARNINGS</th>
      <th>TOTAL BETS COMPLETED</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td><%= number_to_currency @bets.map(&:gross_bet_earnings).sum %></td>
      <td>
        <span class="label label-won"> <%= "#{@bets.where(:state => "won").count} / WON" %>  </span>
        <span class="label label-lost"> <%= "#{@bets.where(:state => "lost").count} / LOST" %>  </span>
      </td>
    </tr>

    </tbody>
  </table>
</div>

app/views/dashboard/update.js.erb
$("#well-content-<%= params[:id] %>").html("<%= escape_javascript(render :partial => "well_content",
 :locals => {:bet => @bet}, :formats => [:html]) %>");

$('.btn-group.open').removeClass('open');