config/routes.rb
Mybet::Application.routes.draw do

  resources :bids
  resources :users

  resources :bets do
    member do
      put :bid
      get :duplicate
    end
    collection do
      get :pending
    end
  end

  root :to => "dashboard#index"

  put "/dashboard/:id/update" => "dashboard#update", :as => "dashboard_update"
  get "/reports" => "dashboard#reporting", :as => "reporting"
  devise_for :users, :path => "/authenticate"

end

app/models/bid.rb
class Bid < ActiveRecord::Base

  belongs_to :bet
  belongs_to :user
  before_create :set_amount
  after_create :set_last_bidder

  private

  def set_amount
    self.position = (bet.bids.count + 1) #TODO do I need to add '+1' ?
    self.amount = self.bet.bid_amount * self.position
  end


  def set_last_bidder
    self.bet.update_attribute("last_bidder_id", self.user_id)
  end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  # GET /bids
  # GET /bids.json
  def index
    @bids = Bid.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bids }
    end
  end

  # GET /bids/1
  # GET /bids/1.json
  def show
    @bid = Bid.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bid }
    end
  end

  # GET /bids/new
  # GET /bids/new.json
  def new
    @bid = Bid.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bid }
    end
  end

  # GET /bids/1/edit
  def edit
    @bid = Bid.find(params[:id])
  end

  # POST /bids
  # POST /bids.json
  def create
    @bid = Bid.new(params[:bid])

    respond_to do |format|
      if @bid.save
        format.html { redirect_to @bid, notice: 'Bid was successfully created.' }
        format.json { render json: @bid, status: :created, location: @bid }
      else
        format.html { render action: "new" }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bids/1
  # PUT /bids/1.json
  def update
    @bid = Bid.find(params[:id])

    respond_to do |format|
      if @bid.update_attributes(params[:bid])
        format.html { redirect_to @bid, notice: 'Bid was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bids/1
  # DELETE /bids/1.json
  def destroy
    @bid = Bid.find(params[:id])
    @bid.destroy

    respond_to do |format|
      format.html { redirect_to bids_url }
      format.json { head :ok }
    end
  end
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/views/bids/_form.html.erb
<%= form_for(@bid) do |f| %>
  <% if @bid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bid.errors.count, "error") %> prohibited this bid from being saved:</h2>

      <ul>
      <% @bid.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bet_id %><br />
    <%= f.number_field :bet_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bids/edit.html.erb
<h1>Editing bid</h1>

<%= render 'form' %>

<%= link_to 'Show', @bid %> |
<%= link_to 'Back', bids_path %>

app/views/bids/index.html.erb
<h1>Listing bids</h1>

<table>
  <tr>
    <th>Bet</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bids.each do |bid| %>
  <tr>
    <td><%= bid.bet_id %></td>
    <td><%= bid.user_id %></td>
    <td><%= link_to 'Show', bid %></td>
    <td><%= link_to 'Edit', edit_bid_path(bid) %></td>
    <td><%= link_to 'Destroy', bid, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bid', new_bid_path %>

app/views/bids/new.html.erb
<h1>New bid</h1>

<%= render 'form' %>

<%= link_to 'Back', bids_path %>

app/views/bids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Bet:</b>
  <%= @bid.bet_id %>
</p>

<p>
  <b>User:</b>
  <%= @bid.user_id %>
</p>


<%= link_to 'Edit', edit_bid_path(@bid) %> |
<%= link_to 'Back', bids_path %>