config/routes.rb
Mybet::Application.routes.draw do

  resources :bids
  resources :users

  resources :bets do
    member do
      put :bid
      get :duplicate
    end
    collection do
      get :pending
    end
  end

  root :to => "dashboard#index"

  put "/dashboard/:id/update" => "dashboard#update", :as => "dashboard_update"
  get "/reports" => "dashboard#reporting", :as => "reporting"
  devise_for :users, :path => "/authenticate"

end

app/models/bet.rb
class Bet < ActiveRecord::Base

  has_many :bids
  belongs_to :user
  belongs_to :last_bidder, :class_name => "User"
  validates :name, :date, :odd_inflation, :original_odds, :bid_amount, :presence => true
  before_save :do_calculations
  before_create :set_user_id

  state_machine :state, :initial => :new do

    event :confirm do
      transition :from => :new, :to => :pending
    end

    event :won do
      transition :from => :pending, :to => :won
    end

    event :lost do
      transition :from => :pending, :to => :lost
    end

    event :back_to_pending do
      transition :from => :won, :to => :pending
      transition :from => :lost, :to => :pending

    end
  end


  def self.won_or_lost
    where(:state => ["won", "lost"])
  end

  # it gets next possible authorized events of current state
  def next_state_events

    t = self.state_transitions(:from => self.state.to_sym)
    authorized_events = Array.new

    t.each do |transition|
      #if (is_authorized_event?(transition.event.to_s, user.role.name, self.state))
      authorized_events << transition
      #end
    end
    authorized_events
  end

  def locked?
    ["won", "lost"].includes?(self.state)
  end


  def bid_amount_of_person(user)
    self.bids.where(:user_id => user.id).sum(:amount)
  end

  def is_last_person?(user)
    self.last_bidder_id == user.id
  end

  def potential_payout
    self.bids.count * self.bid_amount * self.final_odds
  end

  def gross_bet_earnings
    case self.state
      when "won"
        (bid_amount_earned) - (self.bids.count * self.bid_amount * self.final_odds)
      when "lost"
        bid_amount_earned
    end
  end


  def duplicate
    _copy = self.dup
    _copy.last_bidder_id = nil
    _copy.save!
  end


  def current_bid_price
    (self.bids.count + 1) * self.bid_amount
  end

  def bid!(current_user = "")
    self.bids.create(:user_id => current_user.id, :amount => current_bid_price)
  end

  def bid_amount_earned
    self.bids.sum(:amount) + self.bid_amount rescue self.bid_amount
  end

  def sum_amount_of_bids
    self.bids.sum(:amount)
  end

  def calculated_final_odds
    self.final_odds * 100
  end

  private

  def do_calculations
    set_final_odds
  end

  def set_final_odds

    if original_odds < 0
      self.final_odds = (-100/original_odds) * odd_inflation
    else
      self.final_odds = (original_odds/100) * odd_inflation
    end

  end


  def set_user_id
    self.user_id = User.current.try(:id)
  end

end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  # GET /bets
  # GET /bets.json
  before_filter :only_admin, :except => [:bid, :pending]

  def index
    redirect_to root_path and return

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bets }
    end
  end

  def pending
    @bets = Bet.where(:state => "pending")
  end

  def duplicate
    @bet = Bet.find(params[:id])
    @bet.duplicate
    flash[:success] = "Successfully duplicated Bet##{@bet.id}"
    redirect_to root_path
  end

  def bid
    @bet = Bet.find(params[:id])
    @bet.bid!(current_user)
    redirect_to request.referer || pending_bets_path
  end


  # GET /bets/1
  # GET /bets/1.json
  def show

    @bet = Bet.find(params[:id])


    redirect_to root_path and return unless @bet.new?
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bet }
    end
  end

  # GET /bets/new
  # GET /bets/new.json
  def new
    @bet = Bet.new(:odd_inflation => 10, :bid_amount => 1)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bet }
    end
  end

  # GET /bets/1/edit
  def edit
    @bet = Bet.find(params[:id])
  end

  # POST /bets
  # POST /bets.json
  def create
    @bet = Bet.new(params[:bet])

    respond_to do |format|
      if @bet.save
        format.html { redirect_to @bet, notice: 'Bet was successfully created.' }
        format.json { render json: @bet, status: :created, location: @bet }
      else
        format.html { render action: "new" }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bets/1
  # PUT /bets/1.json
  def update
    @bet = Bet.find(params[:id])

    respond_to do |format|
      if @bet.update_attributes(params[:bet])
        format.html { redirect_to @bet, notice: 'Bet was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bets/1
  # DELETE /bets/1.json
  def destroy
    @bet = Bet.find(params[:id])
    @bet.destroy
    flash[:success] = "Successfully deleted!"
    respond_to do |format|
      format.html { redirect_to bets_url }
      format.js { render 'destroy' }
      format.json { head :ok }
    end
  end
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/views/bets/_form.html.erb
<%= form_for @bet, :html => {:class => 'form-horizontal'} do |f| %>
    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :date, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :date, :class => 'datepicker', :size => "16" %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :original_odds, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :original_odds, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :odd_inflation, :class => 'control-label' %>
      <div class="controls">
        <label class="radio">
          <%= f.radio_button :odd_inflation, 10.0, :class => 'radio_input' %>  10x
        </label>
        <label class="radio">
          <%= f.radio_button :odd_inflation, 20.0, :class => 'radio_input' %>  20x
        </label>
        <label class="radio">
          <%= f.radio_button :odd_inflation, 50.0, :class => 'radio_input' %>  50x
        </label>
        <label class="radio">
          <%= f.radio_button :odd_inflation, 100.0, :class => 'radio_input' %>  100x
        </label>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :bid_amount, :class => 'control-label' %>
      <div class="controls">
        <div>
          <label class="radio">
            <%= f.radio_button :bid_amount, 1.0, :class => 'text_field' %>  $1
          </label>
          <label class="radio">

            <%= f.radio_button :bid_amount, 5.0, :class => 'text_field' %>  $5
          </label>
          <label class="radio">

            <%= f.radio_button :bid_amount, 10.0, :class => 'text_field' %>  $10
          </label>
          <label class="radio">

            <%= f.radio_button :bid_amount, 25.0, :class => 'text_field' %>  $25
          </label>
          <label class="radio">

            <%= f.radio_button :bid_amount, 50.0, :class => 'text_field' %>  $50
          </label>

        </div>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :description, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :description, :class => 'text_area', :rows => "5" %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  root_path, :class => 'btn' %>
    </div>
<% end %>

app/views/bets/destroy.js.erb
$('#well-content-<%= params[:id] %>').remove();

$('#main-content').prepend('<%= (escape_javascript(bootstrap_flash)) %>');

app/views/bets/edit.html.erb
<%- model_class = Bet -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bets/index.html.erb
<%- model_class = Bet -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%= model_class.human_attribute_name(:original_odds) %></th>
      <th><%= model_class.human_attribute_name(:final_odds) %></th>
      <th><%= model_class.human_attribute_name(:odd_inflation) %></th>
      <th><%= model_class.human_attribute_name(:bid_amount) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:state) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @bets.each do |bet| %>
      <tr>
        <td><%= link_to bet.id, bet_path(bet) %></td>
        <td><%= bet.name %></td>
        <td><%= bet.date %></td>
        <td><%= bet.original_odds %></td>
        <td>+<%= number_with_precision bet.calculated_final_odds, :precision => 2 %></td>
        <td><%= bet.odd_inflation %></td>
        <td><%= bet.bid_amount %></td>
        <td><%= bet.description %></td>
        <td><%= bet.state %></td>
        <td><%= bet.user_id %></td>
        <td><%=l bet.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_bet_path(bet), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      bet_path(bet),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_bet_path,
            :class => 'btn btn-primary' %>

app/views/bets/new.html.erb
<%- model_class = Bet -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bets/pending.html.erb
<div class="page-header">
  <h1>Pending Bets</h1>
</div>

<table class="table table-striped table-bordered">
  <thead>
  <tr>
    <th>Name</th>
    <th>Current Bidder</th>
    <th>Bid Amount</th>
    <th>Bids Count</th>
    <th>Current Bid</th>
    <th>Potential Payout</th>
    <th>Bet Multiplier</th>
    <th>Final Odds</th>
    <th>Actions</th>
  </tr>
  <tbody>
  <% @bets.each do |bet| %>
      <tr>
        <td><%= bet.name %></td>
        <td><%= bet.last_bidder.try(:username) %></td>
        <td><%= number_to_currency bet.bid_amount %></td>
        <td><%= bet.bids.count %></td>
        <td><%= number_to_currency bet.current_bid_price %></td>
        <td><%= number_to_currency bet.potential_payout %></td>
        <td><%= bet.odd_inflation.to_i %></td>
        <td>+<%= number_with_precision bet.calculated_final_odds, :precision => 2 %></td>
        <td><%= link_to_with_icon "icon-ok", "Bid", bid_bet_path(bet), :class => "btn btn-small btn-primary", :method => :put, :confirm => "Are you sure?" %></td>
      </tr>
  <% end %>
  </tbody>
  </thead>
</table>

app/views/bets/show.html.erb
<%- model_class = Bet -%>
<div class="page-header">
  <h1><%=t '.title', :default => "#{model_class.model_name.human.titleize}##{@bet.id}" %></h1>
  <%= form_for @bet, :html => {:class => 'form-horizontal'} do |f| %>
      <%= f.hidden_field :state, :value => "pending" %>
      <%= f.submit "Confirm", :class => "btn btn-primary" %>
  <% end %>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @bet.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= @bet.date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:original_odds) %>:</strong></dt>
  <dd><%= @bet.original_odds %></dd>
  <dt><strong><%= model_class.human_attribute_name(:odd_inflation) %>:</strong></dt>
  <dd><%= @bet.odd_inflation %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bid_amount) %>:</strong></dt>
  <dd><%= @bet.bid_amount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @bet.description %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_bet_path(@bet), :class => 'btn' %>                    or
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              bet_path(@bet),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>