config/routes.rb
Mybet::Application.routes.draw do

  resources :bids
  resources :users

  resources :bets do
    member do
      put :bid
      get :duplicate
    end
    collection do
      get :pending
    end
  end

  root :to => "dashboard#index"

  put "/dashboard/:id/update" => "dashboard#update", :as => "dashboard_update"
  get "/reports" => "dashboard#reporting", :as => "reporting"
  devise_for :users, :path => "/authenticate"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "MyBet" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>


  <%= javascript_include_tag "application" %>
</head>
<body>
<div id="wrap">

  <div class="navbar navbar-fluid-top navbar-inverse">
    <div class="navbar-inner">
      <div class="container-fluid">
        <a class="brand" href="<%= root_path %>">MyBet</a>
        <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>

        <div class="container-fluid nav-collapse ">
          <ul class="nav pull-right">
            <% if @current_user %>
                <% if @current_user.has_role?('admin') %>
                    <li><%= link_to "Create Bet", new_bet_path %> </li>
                <% end %>
                <li><%= link_to "Pending Bets", pending_bets_path %> </li>
                <% if @current_user.has_role?('admin') %>
                    <li><%= link_to "Dashboard", root_path %> </li>
                    <li><%= link_to "Reporting", reporting_path %> </li>
                <% end %>

                <li><%= link_to "My Account", edit_user_registration_path %> </li>
                <li><%= link_to "Logout", destroy_user_session_path, :method => "delete" %> </li>
            <% end %>
          </ul>
        </div>
        <!--/.nav-collapse -->
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="span12" id="main-content">
        <%= bootstrap_flash %>
        <%= yield %>
      </div>
    </div>
    <!--/row-->
  </div>
  <!-- /container -->
</div>
<!-- /wrap -->
<div id="footer">
  <div class="container">
    <p class="footer-content">&copy; MyBet <%= Date.today.year %></p>
  </div>
</div>
</body>
</html>